factura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('invoice.urls')),
    path('loan/', include('loan.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Facturación"

loan/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    # Post views
    path('', views.loan, name='loan'),
    path('list/', login_required(views.LoanList.as_view()), name='loan_list'),
    path('create/', views.LoanCreate.as_view(), name='loan_create'),
    path('get_period_value/', views.get_period_value, name='get_period_value'),
]

loan/models.py
from django.db import models
from django.utils.timezone import now

from company.models import Company
from customer.models import Customer


class PaymentPeriod(models.Model):
    name = models.CharField(verbose_name="Periodo de Pago", max_length=30)
    value = models.DecimalField(verbose_name="Valor", max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = "Periodo de Pago"
        verbose_name_plural = "Periodos de Pago"

    def __str__(self):
        return self.name


class Loan(models.Model):
    STATUS_CHOICES = (
        ('paying', 'Por Pagar'),
        ('cancelled', 'Cancelado'),
    )
    company = models.ForeignKey(Company, verbose_name="Compañia", on_delete=models.PROTECT, blank=True, null=True)
    customer = models.ForeignKey(Customer, verbose_name="Cliente", on_delete=models.CASCADE, blank=True, null=True)
    payment_period = models.ForeignKey(PaymentPeriod, verbose_name="Periodo de pago", on_delete=models.PROTECT)
    cost = models.DecimalField(verbose_name="Costo", max_digits=10, decimal_places=2)
    initial_fee = models.DecimalField(verbose_name="Cuota inicial", max_digits=10, decimal_places=2)
    taxes = models.DecimalField(verbose_name="Impuestos", max_digits=10, decimal_places=2)
    total_periods = models.IntegerField(verbose_name="Total periodos")
    date = models.DateField(verbose_name="Fecha de compra", default=now)
    expiration_date = models.DateField(verbose_name="Fecha de vencimiento", blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='paying', verbose_name="Estado")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Prestamo"
        verbose_name_plural = "Prestamos"
        ordering = ['created']

    def __str__(self):
        return self.customer.name

loan/forms.py
from django import forms

from customer.models import Customer
from loan.models import PaymentPeriod, Loan


class LoanForm(forms.Form):
    cost = forms.DecimalField(label="Costo")
    initial_fee = forms.DecimalField()
    taxes = forms.DecimalField()
    total_periods = forms.IntegerField()
    payment_period = forms.ModelChoiceField(queryset=PaymentPeriod.objects.all(), widget=forms.Select(
        attrs={'class': 'form-control form-control-alternative'}
    ), empty_label="Seleccione un periodo de pago")


class LoanCreateForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ('customer', 'cost', 'initial_fee', 'taxes', 'total_periods', 'date', 'payment_period')
        widgets = {
            'customer': forms.Select(attrs={'class':'form-control form-control-alternative'}),
            'cost': forms.NumberInput(attrs={'class':'form-control form-control-alternative'}),
            'initial_fee': forms.NumberInput(attrs={'class':'form-control form-control-alternative'}),
            'taxes': forms.NumberInput(attrs={'class':'form-control form-control-alternative'}),
            'total_periods': forms.NumberInput(attrs={'class':'form-control form-control-alternative'}),
            'date': forms.SelectDateWidget(attrs={'class':'form-control form-control-alternative'}),
            'payment_period': forms.Select(attrs={'class':'form-control form-control-alternative'}),
        }

    def __init__(self, *args, **kwargs):
        super(LoanCreateForm, self).__init__(*args, **kwargs)
        self.fields['payment_period'].empty_label = "Seleccione el periodo de pago"
        self.fields['customer'].empty_label = "Seleccione un cliente"

loan/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from invoice.models import Invoice, DetailInvoice
from loan.forms import LoanForm, LoanCreateForm
from . import forms
from loan.models import PaymentPeriod, Loan
from django.views.generic import CreateView, ListView
from datetime import datetime, date, time, timedelta
import calendar


@login_required
def loan(request):
    loan_form = LoanForm()
    return render(request, 'loan/loan.html', {'loan_form': loan_form})


@login_required
@require_POST
def get_period_value(request):
    payment_period = request.POST['payment_period']
    period = PaymentPeriod.objects.get(id=payment_period)
    value = period.value
    return JsonResponse({'data': value})


class LoanList(ListView):
    model = Loan
    template_name = 'loan/loan_list.html'
    context_object_name = 'loans'

    def get_queryset(self):
        return Loan.objects.filter(company=self.request.user.company)


def get_expiration_date(purchase_date, total_period, period):
    return purchase_date + timedelta(days=((360 / int(period.value)) * total_period))


class LoanCreate(CreateView):
    model = Loan
    template_name = "loan/loan_create.html"
    form_class = LoanCreateForm
    success_url = reverse_lazy('loan_list')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = self.get_object

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            my_loan = form.save()
            total_period = cd['total_periods']
            period = cd['payment_period']
            cost = cd['cost']
            initial_fee = cd['initial_fee']
            taxes = cd['taxes']
            debt = (cost-initial_fee)
            my_loan.company = request.user.company
            my_loan.expiration_date = get_expiration_date(cd['date'], total_period, period)
            my_loan.save()
            initial_invoice = Invoice(
                loan=my_loan,
                payment_date=cd['date'],
                subtotal=initial_fee,
                tax=0,
            )
            initial_invoice.save()
            initial_detail_invoice = DetailInvoice(
                invoice=initial_invoice,
                description="Pago inicial",
                value=initial_fee,
            )
            initial_detail_invoice.save()
            for i in range(int(total_period)):
                subtotal = (cost-initial_fee) / total_period
                tax = debt*(taxes/100)*(1/period.value)
                new_invoice = Invoice(
                    loan=my_loan,
                    payment_date=get_expiration_date(cd['date'], i + 1, period),
                    subtotal=subtotal,
                    tax=tax,
                )
                new_invoice.save()
                new_detail_invoice = DetailInvoice(
                    invoice=new_invoice,
                    description="Pago por compra",
                    value=subtotal,
                )
                debt = debt - ((cost-initial_fee) / total_period)
                new_detail_invoice.save()
                new_invoice.save()
            return HttpResponseRedirect(self.get_success_url())

loan/templates/loan/loan.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Compras{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Datos</h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form id="loan_form">
                        {% csrf_token %}
                        <h6 class="heading-small text-muted mb-4">Ingrese los siguientes datos</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_cost">Costo ($)</label>
                                        <input type="number" name="cost" step="0.01" id="id_cost" class="form-control form-control-alternative" required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_initial_fee">Pago inicial ($)</label>
                                        <input type="number" step="0.01" id="id_initial_fee" name="initial_fee" class="form-control form-control-alternative" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_taxes">Impuesto (%)</label>
                                        <input type="number" step="0.01" id="id_taxes" name="taxes" class="form-control form-control-alternative" required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_total_periods">Total periodos</label>
                                        <input type="number" id="id_total_periods" class="form-control form-control-alternative" name="total_periods">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_payment_period">Periodo de Pago</label>
                                        {{ loan_form.payment_period }}
                                    </div>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-lg-12">
                                    <input type="submit" class="btn btn-primary text-center" value="Calcular">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
    <!-- Table -->
    <div class="row" id="loan_table">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Lista de Pagos</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Cuota Mensual</th>
                            <th scope="col">Valor Deuda</th>
                            <th scope="col">Intereses</th>
                            <th scope="col">Pago Final</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <nav aria-label="...">
                        <h3 class="text-right mb-0">Pago total: <span class="mb-0" id="total_value"></span></h3>
                    </nav>
                    <nav aria-label="...">
                        <h3 class="text-right mb-0">Total impuestos: <span class="mb-0" id="total_taxes"></span></h3>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    {% block javascript %}
        <script type="text/javascript">
            $(document).on('submit', '#loan_form', function (e) {
                e.preventDefault();
                var select = document.getElementById("id_payment_period");
                var cost = $('#id_cost').val();
                var initial_fee = $('#id_initial_fee').val();
                var taxes = $('#id_taxes').val();
                var total_periods = $('#id_total_periods').val();
                var payment_period = select.options[select.selectedIndex].value;
                var period_value = 0.00;
                var total_value = 0.00;
                var total_taxes = 0.00;
                var mensual_cuote = (cost-initial_fee)/total_periods;
                var table = document.getElementById("loan_table").getElementsByTagName('tbody')[0];
                while(table.hasChildNodes())
                {
                    table.removeChild(table.firstChild);
                }
                $.ajax({
                    type: 'POST',
                    url: '/loan/get_period_value/',
                    data:{
                        payment_period: select.options[select.selectedIndex].value,
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function (data) {
                        period_value = data.data;
                        for (var i=0; i<=total_periods; i++){
                            var number = "<td>" + i + "</td>";
                            if (i==0){
                                var mensual_cuote_html = "<td>" + roundToTwo(0.00) + "</td>";
                                var debt_value = (cost-initial_fee);
                                var tax = (cost-initial_fee)*(taxes/100)*(1/period_value);
                                var final_value = initial_fee;
                                var last_tax = tax;
                            } else{
                                mensual_cuote_html = "<td>" + roundToTwo(mensual_cuote) + "</td>";
                                debt_value = debt_value - mensual_cuote;
                                var tax = debt_value*(taxes/100)*(1/period_value);
                                final_value = mensual_cuote + last_tax;
                                last_tax = tax;
                            }
                            total_taxes = Number(total_taxes) + Number(tax);
                            total_value = Number(total_value) + Number(final_value);
                            var debt_value_html = "<td>" + roundToTwo(debt_value) + "</td>";
                            var tax_html = "<td>" + roundToTwo(tax) + "</td>";
                            var final_value_html = "<td>" + roundToTwo(final_value) + "</td>";
                            var total = number + mensual_cuote_html + debt_value_html + tax_html + final_value_html;
                            var row = table.insertRow(table.rows.length);
                            row.innerHTML = total;
                        }
                        document.getElementById("total_value").innerHTML = roundToTwo(total_value);
                        document.getElementById("total_taxes").innerHTML = roundToTwo(total_taxes);
                    }
                });
            });
            function roundToTwo(num) {
                return +(Math.round(num + "e+2")  + "e-2");
            }
        </script>
    {% endblock %}
{% endblock %}

loan/templates/loan/loan_create.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Compras{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Datos</h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h6 class="heading-small text-muted mb-4">Ingrese los siguientes datos</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_customer">Cliente</label>
                                        {{ form.customer }}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_cost">Costo ($)</label>
                                        {{ form.cost }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_initial_fee">Pago inicial ($)</label>
                                        {{ form.initial_fee }}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_taxes">Impuesto (%)</label>
                                        {{ form.taxes }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_total_periods">Total periodos</label>
                                        {{ form.total_periods }}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_payment_period">Periodo de Pago</label>
                                        {{ form.payment_period }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_date">Fecha</label>
                                        {{ form.date }}
                                    </div>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-lg-12">
                                    <input type="submit" class="btn btn-primary text-center" value="Guardar">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

loan/templates/loan/loan_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Préstamos-Compras{% endblock %}
{% block content %}
    <!-- Table -->
    <div class="row" id="loan_table">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Lista de Pagos</h3>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Page name</th>
                            <th scope="col">Visitors</th>
                            <th scope="col">Unique users</th>
                            <th scope="col">Bounce rate</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for loan in loans %}
                        {% empty %}
                        {% endfor %}
                        <tr>
                            <th scope="row">
                                /argon/
                            </th>
                            <td>
                                4,569
                            </td>
                            <td>
                                340
                            </td>
                            <td>
                                <i class="fas fa-arrow-up text-success mr-3"></i> 46,53%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                /argon/index.html
                            </th>
                            <td>
                                3,985
                            </td>
                            <td>
                                319
                            </td>
                            <td>
                                <i class="fas fa-arrow-down text-warning mr-3"></i> 46,53%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                /argon/charts.html
                            </th>
                            <td>
                                3,513
                            </td>
                            <td>
                                294
                            </td>
                            <td>
                                <i class="fas fa-arrow-down text-warning mr-3"></i> 36,49%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                /argon/tables.html
                            </th>
                            <td>
                                2,050
                            </td>
                            <td>
                                147
                            </td>
                            <td>
                                <i class="fas fa-arrow-up text-success mr-3"></i> 50,87%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                /argon/profile.html
                            </th>
                            <td>
                                1,795
                            </td>
                            <td>
                                190
                            </td>
                            <td>
                                <i class="fas fa-arrow-down text-danger mr-3"></i> 46,53%
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}